build: false
platform:
  - x64
clone_folder: C:\Projects\OroPlatform

init:
    - SET PATH=C:\PHP;C:\bin;%PATH%
    - SET COMPOSER_NO_INTERACTION = 1

install:
    # PHP
    - mkdir C:\PHP && cd C:\PHP
    - appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php-7.1.3-Win32-VC14-x86.zip
    - 7z x php-7.1.3-Win32-VC14-x86.zip -y >nul
    - copy /Y php.ini-development php.ini
    - echo memory_limit=-1 >> php.ini
    - echo max_execution_time=1200 >> php.ini
    - echo date.timezone="America/Los_Angeles" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo zend_extension=php_opcache.dll >> php.ini
    - echo opcache.enable_cli=1 >> php.ini
    - echo extension=php_bz2.dll >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension=php_exif.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - echo extension=php_gd2.dll >> php.ini
    - echo extension=php_gmp.dll >> php.ini
    - echo extension=php_imap.dll >> php.ini
    - echo extension=php_intl.dll >> php.ini
    - echo extension=php_ldap.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_pdo_mysql.dll >> php.ini
    - echo extension=php_soap.dll >> php.ini
    - echo extension=php_sockets.dll >> php.ini
    - echo extension=php_tidy.dll >> php.ini
    - echo extension=php_xmlrpc.dll >> php.ini

    - mkdir C:\bin

    # PHPUnit
    - cd C:\bin
    - appveyor DownloadFile https://phar.phpunit.de/phpunit-5.7.phar
    - echo @php "%~dp0phpunit-5.7.phar" %* > phpunit.cmd

    # Composer
    - cd C:\bin
    - appveyor DownloadFile https://getcomposer.org/download/1.6.3/composer.phar
    - echo @php -dmemory_limit=-1 "%~dp0composer.phar" %* > composer.cmd
    # - composer self-update

    # Dependencies
    - IF %APPVEYOR_REPO_BRANCH%==master (SET COMPOSER_ROOT_VERSION=dev-master) ELSE (SET COMPOSER_ROOT_VERSION=%APPVEYOR_REPO_BRANCH%.x-dev)
    - composer install--no-progress --no-suggest --ansi
    - composer dump-autoload

test_script:
    - phpunit --testsuite unit
